name: moviemap
description: "A movie, series, and more explorer app."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  animate_do: ^3.3.4
  card_swiper: ^3.0.1
  dio: ^5.6.0
  flutter_dotenv: ^5.1.0
  flutter_lints: ^4.0.0
  flutter_riverpod: ^2.5.1
  flutter_test:
    sdk: flutter
  go_router: ^14.2.3
  intl: ^0.19.0

flutter:
  uses-material-design: true
  assets:
    - .env
